_wandb:
    value:
        cli_version: 0.22.3
        e:
            x0s91gw8mt93v976cknq2157zl03c81o:
                codePath: current_models/baseline_model_v2.py
                codePathLocal: baseline_model_v2.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "765889540096"
                        used: "15685234688"
                email: hyewona@mit.edu
                executable: /orcd/home/002/hyewona/lr-act/lora/bin/python3
                git:
                    commit: 360f6df6f3663f1a3dc490433e3ee9f0963ab87b
                    remote: git@github.mit.edu:hyewona/lr_activations.git
                gpu: NVIDIA L40S
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-041f4aa4-3cf8-020a-63d3-3303872b79bd
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-3f938222-078c-2ea6-9f4d-cd0fecc6ac3a
                host: node3203
                memory:
                    total: "1081411747840"
                os: Linux-4.18.0-372.9.1.el8.x86_64-x86_64-with-glibc2.28
                program: /orcd/home/002/hyewona/lr-act/current_models/baseline_model_v2.py
                python: CPython 3.13.5
                root: /orcd/home/002/hyewona/lr-act/current_models
                slurm:
                    cluster_name: eofe7
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "4"
                    cpus_per_task: "4"
                    gpus_on_node: "2"
                    gtids: "0"
                    job_account: mit_general
                    job_cpus_per_node: "4"
                    job_end_time: "1765473472"
                    job_gid: "100208845"
                    job_gpus: 2,3
                    job_id: "7114186"
                    job_name: interactive
                    job_nodelist: node3203
                    job_num_nodes: "1"
                    job_partition: mit_normal_gpu
                    job_qos: normal
                    job_start_time: "1765471672"
                    job_uid: "208845"
                    job_user: hyewona
                    jobid: "7114186"
                    launch_node_ipaddr: 10.1.221.1
                    localid: "0"
                    mem_per_node: "12288"
                    mpi_type: none
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: node3203
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "39719"
                    pty_win_col: "191"
                    pty_win_row: "43"
                    script_context: prolog_task
                    srun_comm_host: 10.1.221.1
                    srun_comm_port: "45597"
                    step_id: "4294967290"
                    step_launcher_port: "45597"
                    step_nodelist: node3203
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "4294967290"
                    submit_dir: /orcd/home/002/hyewona/lr-act
                    submit_host: orcd-login001.mit.edu
                    task_pid: "4011112"
                    tasks_per_node: "1"
                    topology_addr: node3203
                    topology_addr_pattern: node
                    tres_per_task: cpu=4
                startedAt: "2025-12-11T16:53:35.770486Z"
                writerId: x0s91gw8mt93v976cknq2157zl03c81o
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 71
            "2":
                - 1
                - 11
                - 49
                - 51
                - 71
            "4": 3.13.5
            "5": 0.22.3
            "6": 4.57.1
            "12": 0.22.3
            "13": linux-x86_64
